parameters:
  image_size: [64, 64]  # [16,16] [32,32] [64,64] [128, 128] [224, 244]
  batch_size: 28  # Number of images processed in a single training batch
  epochs: 20  # Increased epochs for longer training cycles with early stopping
  rescale: 0.00392156862745098  # Normalize pixel values to the range [0, 1]
  validation_split: 0.2  # Fraction of the training data reserved for validation
  optimizer:
    type: "Adam"  # Optimizer type: Adam
    learning_rate: 0.0001  # Initial learning rate
    warmup_epochs: 3  # Warmup period for smoother gradient updates
    momentum: 0.9  # Momentum (not used for Adam but retained for modularity)
    beta_1: 0.9  # Decay rate for the first moment in Adam
    beta_2: 0.999  # Decay rate for the second moment in Adam
    epsilon: 1e-7  # Small constant to prevent division by zero
  lr_scheduler:
    enable: true  # Enable learning rate scheduling
    monitor: "val_loss"  # Metric for reducing learning rate
    factor: 0.5  # Reduce learning rate by 50% when no improvement
    patience: 3  # Number of epochs without improvement before adjustment
    min_lr: 0.00001  # Minimum allowed learning rate
  regularization:
    l2: 0.004  # L2 regularization for weight decay
    l1: 0.002  # L1 regularization for sparsity

  dropout_rate: 0.3  # Increased dropout rate for improved generalization
  conv_filters:
    conv1_filters: 64
    conv2_filters: 128
    conv3_filters: 256
  dense_units:
    dense1_units: 256
    dense2_units: 128
  dropout_rates:
    dropout1: 0.4  # Best Value So Far
    dropout2: 0.5  # Best Value So Far
    dropout3: 0.4  # Best Value So Far
    dropout4: 0.5  # Best Value So Far

class_weights:
  male: 1.0  # Adjust weights for class imbalance
  female: 1.0  # Default weight for balanced classes

directories:
  data_dir: "gender-training-dataset"  # Path to the main dataset directory
  female_dir: "gender-training-dataset/female_augmented"  # Augmented female images directory
  male_dir: "gender-training-dataset/male_augmented"  # Augmented male images directory
  test_set_male: "test-set-male"  # Male test set directory
  test_set_female: "test-set-female"  # Female test set directory

logs:
  tensorboard:
    enable: true  # Enable TensorBoard for visualization
    log_dir: "logs/gender_model_v2"  # Updated log directory
    histogram_freq: 1  # Frequency (in epochs) for logging histograms

model:
  path: "best_gender_model_v2.keras"  # Updated file path for saving the best model
  checkpoint:
    enable: true  # Enable model checkpoints
    filepath: "checkpoints/best_gender_model_v2.keras"  # Save checkpoints in a separate directory
    monitor: "val_loss"  # Save the best model based on validation loss
    save_best_only: true  # Save only if the model improves
    early_stopping:
      monitor: "val_loss"  # Monitor validation loss for early stopping
      patience: 5  # Stop training after 5 epochs without improvement
      restore_best_weights: true  # Restore weights from the best epoch

seed: 42  # Set a fixed seed for reproducibility

data_generators:
  enable_augmentation: true  # Enable data augmentation for improved generalization
  augmentation_params:
    rotation_range: 40  # Increased rotation range for more variability
    width_shift_range: 0.4  # Allow larger horizontal shifts
    height_shift_range: 0.4  # Allow larger vertical shifts
    shear_range: 0.3  # Increase shear transformations
    zoom_range: 0.5  # Increased zoom range for more diverse inputs
    horizontal_flip: true  # Enable horizontal flipping for augmentation
    brightness_range: [0.7, 1.3]  # Random brightness adjustments
