parameters:
  image_size: [64, 64]  # Input size of the images (height, width)
  batch_size: 64  # Number of images processed in a single training batch
  epochs: 15  # Allow more epochs but use early stopping to prevent overfitting
  rescale: 0.00392156862745098  # Pixel value rescaling factor (e.g., 1.0/255 to normalize to [0, 1])
  validation_split: 0.2  # Fraction of the training data reserved for validation
  optimizer:
    type: "Adam"  # Optimizer type: SGD (Stochastic Gradient Descent), Adam, etc.
    learning_rate: 0.0005  # Step size for weight updates
    momentum: 0.9  # Momentum for SGD to accelerate gradient descent
    beta_1: 0.9  # Decay rate for the first moment in Adam (not used for SGD)
    beta_2: 0.999  # Decay rate for the second moment in Adam (not used for SGD)
    epsilon: 1e-7  # Small constant to prevent division by zero (Adam-specific)
  lr_scheduler:
    enable: true  # Enable learning rate reduction on plateau
    monitor: "val_loss"  # Metric to monitor for reducing learning rate
    factor: 0.5  # Reduce learning rate by 50% when no improvement
    patience: 2  # Number of epochs with no improvement before reducing learning rate
    min_lr: 0.00001  # Minimum allowed learning rate
  regularization:
    l2: 0.005  # Increased L2 regularization to reduce overfitting
    l1: 0.001  # Added L1 regularization for sparsity
  dense_units: [256, 128]  # Slightly increased model complexity to capture more patterns
  dropout_rate: 0.5  # Reduced dropout for better balance between regularization and learning

  class_weights:
    male: 1.2  # Adjust weights if class imbalance exists
    female: 1.0  # Default weight for balanced classes
directories:
  female_dir: "gender-training-dataset/female_augmented"  # Path to the augmented female images
  male_dir: "gender-training-dataset/male_augmented"  # Path to the augmented male images
  test_set_male: "test-set-male"  # Path to the male test set
  test_set_female: "test-set-female"  # Path to the female test set
logs:
  tensorboard:
    enable: true  # Enable TensorBoard logging
    log_dir: "logs/gender_model_v1"  # Directory to save TensorBoard logs
    histogram_freq: 1  # Frequency (in epochs) to log histograms of layer weights
model:
  path: "best_gender_model.keras"  # File path to save the best-trained model
  checkpoint:
    enable: true  # Enable saving model checkpoints
    filepath: "best_gender_model.keras"  # File path for saving model checkpoints
    monitor: "val_loss"  # Metric to monitor for saving the best model
    save_best_only: true  # Save the model only if it improves the monitored metric
    early_stopping:
      monitor: "val_loss"  # Monitor validation loss for early stopping
      patience: 3  # Stop training after 3 epochs of no improvement
      restore_best_weights: true  # Restore weights from the best-performing epoch
seed: 42  # Random seed for reproducibility

data_generators:
  enable_augmentation: true  # Enable data augmentation for better generalization
  augmentation_params:
    rotation_range: 20  # Increase rotation range for more variability
    width_shift_range: 0.2  # Allow larger width shifts
    height_shift_range: 0.2  # Allow larger height shifts
    shear_range: 0.2  # Increase shear for more variability
    zoom_range: 0.3  # Increase zoom for more diverse inputs
    horizontal_flip: true  # Flip images horizontally
