parameters:
  image_size: [64, 64]  # Input size of the images (height, width)
  batch_size: 64  # Number of images processed in a single training batch
  epochs: 7  # Reduce epochs to prevent overfitting
  rescale: 0.00392156862745098 # Pixel value rescaling factor (e.g., 1.0/255 to normalize to [0, 1])
  validation_split: 0.2  # Fraction of the training data reserved for validation
  optimizer:
    type: "Adam"  # Optimizer type: SGD (Stochastic Gradient Descent), Adam, etc.
    learning_rate: 0.0005  # Step size for weight updates
    momentum: 0.9  # Momentum for SGD to accelerate gradient descent
    beta_1: 0.9  # Decay rate for the first moment in Adam (not used for SGD)
    beta_2: 0.999  # Decay rate for the second moment in Adam (not used for SGD)
    epsilon: 1e-7  # Small constant to prevent division by zero (Adam-specific)
  lr_scheduler:
    enable: true  # Enable learning rate reduction on plateau
    monitor: "val_loss"  # Metric to monitor for reducing learning rate
    factor: 0.3  # Reduce learning rate by 30% when no improvement
    patience: 2  # Number of epochs with no improvement before reducing learning rate
    min_lr: 0.00001  # Minimum allowed learning rate
  regularization:
    l2: 0.005  # Increased L2 regularization factor to reduce overfitting
    l1: 0.001  # L1 regularization factor remains at 0.0 for sparsity
  dense_units: [128]  # Simplified model by reducing the number of dense units
  dropout_rate: 0.6  # Increased dropout to 60% for better regularization

  class_weights:
    male: 1.0  # Weight for the male class in imbalanced datasets
    female: 1.0  # Weight for the female class in imbalanced datasets
directories:
  female_dir: "gender-training-dataset/female_augmented"  # Path to the augmented female images
  male_dir: "gender-training-dataset/male_augmented"  # Path to the augmented male images
  test_set_male: "test-set-male"  # Path to the male test set
  test_set_female: "test-set-female"  # Path to the female test set
logs:
  tensorboard:
    enable: true  # Enable TensorBoard logging
    log_dir: "logs/gender_model_v1"  # Directory to save TensorBoard logs
    histogram_freq: 1  # Frequency (in epochs) to log histograms of layer weights
model:
  path: "best_gender_model.keras"  # File path to save the best-trained model
  checkpoint:
    enable: true  # Enable saving model checkpoints
    filepath: "best_gender_model.keras"  # File path for saving model checkpoints
    monitor: "val_loss"  # Metric to monitor for saving the best model
    save_best_only: true  # Save the model only if it improves the monitored metric
seed: 42  # Random seed for reproducibility

data_generators:
  enable_augmentation: true  # Enable data augmentation for better generalization
  augmentation_params:
    rotation_range: 15  # Rotate images by up to 15 degrees
    width_shift_range: 0.1  # Shift width by up to 10%
    height_shift_range: 0.1  # Shift height by up to 10%
    shear_range: 0.15  # Apply shearing transformations
    zoom_range: 0.2  # Randomly zoom images by 20%
    horizontal_flip: true  # Flip images horizontally
