class_weights:
  calculate: auto
data_generators:
  augmentation_params:
    brightness_range:
    - 0.95
    - 1.05
    fill_mode: nearest
    height_shift_range: 0.02
    horizontal_flip: true
    rotation_range: 5
    shear_range: 0.05
    width_shift_range: 0.02
    zoom_range: 0.05
  enable_augmentation: true
directories:
  data_dir: gender-training-dataset
  female_dir: gender-training-dataset/female_augmented
  male_dir: gender-training-dataset/male_augmented
  test_set_female: test-set-female
  test_set_male: test-set-male
hyperparameter_ranges:
  conv_filters:
  - 32
  - 128
  dense_units:
  - 64
  - 512
  dropout_rate:
  - 0.1
  - 0.3
  kernel_size:
  - 3
  - 5
  num_conv_layers:
  - 2
  - 4
keras:
  keras_max_epochs: 20
  keras_max_trials: 10
logs:
  detailed_logs_path: logs/detailed_training_logs.csv
  log_dir: logs/gender_model_v2
  save_logs: false
  tensorboard:
    enable: true
    histogram_freq: 1
model:
  checkpoint:
    early_stopping:
      monitor: val_loss
      patience: 5
      restore_best_weights: true
    enable: true
    filepath: checkpoints/best_gender_model_v2.keras
    monitor: val_loss
    save_best_only: true
  path: best_gender_model_v2.keras
parameters:
  batch_size: 32
  conv1_filters: 32
  conv2_filters: 32
  conv3_filters: 384
  dense1_units: 128
  dense2_units: 256
  dropout1: 0.1
  dropout2: 0.2
  dropout3: 0.1
  dropout4: 0.2
  dropout_rate: 0.3
  dropout_rates:
    conv_layers: 0.2
    dense_layers: 0.3
  epochs: 20
  image_size:
  - 64
  - 64
  learning_rate: 0.001
  lr_scheduler:
    decay_rate: 0.9
    decay_steps: 1000
    enable: true
    initial_learning_rate: 0.001
    min_lr: 1.0e-05
    type: ExponentialDecay
  optimizer:
    beta_1: 0.9
    beta_2: 0.999
    epsilon: 1e-7
    learning_rate: 0.001
    type: Adam
    warmup_epochs: 5
  regularization:
    l1: 0.0001
    l2: 0.001
  rescale: 0.00392156862745098
  test_size: 0.1
  threshold: 0.5
  validation_split: 0.2
  validation_strategy:
    type: split
    validation_split: 0.2
seed: 42
